// <auto-generated />
using GameAPICore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameAPICore.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20190323164309_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameAPICore.Models.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlayerOneName")
                        .HasMaxLength(50);

                    b.Property<int>("PlayerOneOption");

                    b.Property<string>("PlayerTwoName")
                        .HasMaxLength(50);

                    b.Property<int>("PlayerTwoOption");

                    b.Property<int>("Round");

                    b.Property<string>("Winner")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("tblGames");
                });
#pragma warning restore 612, 618
        }
    }
}
